name: ci

on: [push, pull_request]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        go: ["^1.15.0"]
        os: [ubuntu-latest, macOS-latest, windows-latest]
    name: Go ${{ matrix.go }} in ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Environment
        run: |
          go version
          go env

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.35.2
          # Optional: working directory, useful for monorepos
          # working-directory: somedir

          # Optional: golangci-lint command line arguments.
          args: -v

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true

      - name: Format
        run: make format-check

      - name: Test
        run: |
          make test
          go mod tidy
          git checkout ./

      - name: Build
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist --skip-publish --skip-validate

  release:
    name: Release to Github
    if: startsWith(github.ref, 'refs/tags/') && github.repository == 'axetroy/fslint'
    needs: [ci]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["^1.15.0"]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - uses: axetroy/setup-whatchanged@v1
        with:
          version: v0.3.4

      - name: Generate release.md
        run: |
          whatchanged --tpl=release.tpl --output=release.md
          cat release.md

      - name: Release to Github
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist --release-notes=./release.md
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Prepare publish
        env:
          GITHUB_REF: ${{ github.ref }}
        run: |
          cp README.md ./npm/README.md
          cp README_zh-CN.md ./npm/README_zh-CN.md
          cp release.md ./npm/CHANGELOG.md
          cp LICENSE ./npm/LICENSE
          cp LICENSE_zh-CN ./npm/LICENSE_zh-CN
          node ./npm/scripts/bump.js

      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          package: ./npm/package.json
          token: ${{ secrets.NPM_TOKEN }}
